version: '3.9'

networks:
  default:
    name: api

services:
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
  
  node-project:
    build: .
    image: node-project
    container_name: node-project
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 8080
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: mernDB
    depends_on:
      - mongo_db
    restart: always
    command: tail -f /dev/null

volumes:
  mongo_db: {}